### ISSUE TITLE
Improved multi-editor support

### ISSUE THREAD

**Issue by randomPoison** [randomPoison/amethyst-editor#4]
#2 introduced multi-window support, allowing us to automatically open a new editor window for each game running on the user's system. This is a good first pass at the desired functionality, but the user experience leaves a lot to be desired.

The following tasks are ways in which we can improve the UX around multi-game/multi-editor setups (including keeping the experience simple for users who only need a single editor at a time):

* [ ] **Create multiple tabs within a root window**, similar to how web browsers and most text editors work. This will reduce confusion since there's only a single window that the user needs to keep track of when new editors are added or removed.
* [ ] **Display an empty "Welcome" screen** when no editors are active. This assures users that the editor is still working when no games are connected, and reminds them that they need to open a game to use the editor.
* [ ] **Allow editors to be "persistent"** by setting up a game to always bind to the same port. This will allow us to keep an editor tab open even if the game is closed or restarted, providing a smoother experience when the user re-compiles their game.

If you have any suggestions for other things that could be done to make working with multiple games/editors more ergonomic, feel free to suggest them here!

**Comment by randomPoison** [comment]
I'm closing this in favor of using projects to track epics: https://github.com/randomPoison/amethyst-editor/projects/2
